name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  bloobit: ^1.0.5-beta
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_ioc_container:
    path: ../
  ioc_container:
    path: ../../ioc_container


dev_dependencies:
  austerity: ^0.0.9-beta
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


