name: flutter_ioc_container
description: A Flutter extension for the ioc_container package
version: 0.0.1-beta
repository: https://github.com/MelbourneDeveloper/flutter_ioc_container
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ioc_container: 
    path: ../ioc_container

dev_dependencies:
  austerity: ^0.0.9-beta
  example:
    path: example
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  
