name: flutter_ioc_container
description: A Flutter extension for the ioc_container package
version: 0.4.0
repository: https://github.com/MelbourneDeveloper/flutter_ioc_container

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ioc_container: ^1.0.8

dev_dependencies:
  austerity: ^1.0.0
  example:
    path: example
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
